import { describe, it, expect } from "vitest";
import { renderToSerializedVNode } from "../src/runtime/serialize";
import { ONIGIRI_RENDER_SYMBOL, VServerComponentType } from "../src/runtime/shared";
import { ref, defineComponent, inject, h } from "vue";

describe("renderToSerializedVNode", () => {
  it("should serialize a component with compiled renderOnigiri", async () => {
    // Simulate a component compiled with ?onigiri
    // In real usage, this would be generated by the Vite plugin
    const TestComponent = defineComponent({
      props: {
        message: String,
      },
      setup(props) {
        const count = ref(0);

        // This is what the Vite plugin injects
        const onigiriMode = inject(ONIGIRI_RENDER_SYMBOL, null);
        if (onigiriMode) {
          // Return the onigiri render function with direct access to bindings
          return () =>
            renderOnigiri({
              message: props.message,
              count: count.value,
            });
        }

        // Normal render (not used in this test)
        return { count };
      },
    });

    // Simulate the compiled renderOnigiri function
    function renderOnigiri(_ctx: { message?: string; count: number }) {
      return [
        VServerComponentType.Element,
        "div",
        { class: "test" },
        [
          [VServerComponentType.Text, _ctx.message || "default"],
          [VServerComponentType.Text, String(_ctx.count)],
        ],
      ] as const;
    }

    const result = await renderToSerializedVNode(TestComponent, {
      message: "Hello Onigiri!",
    });

    expect(result).toBeDefined();
    expect(result).toEqual([
      VServerComponentType.Element,
      "div",
      { class: "test" },
      [
        [VServerComponentType.Text, "Hello Onigiri!"],
        [VServerComponentType.Text, "0"],
      ],
    ]);
  });

  it("should fallback to runtime serialization without renderOnigiri", async () => {
    // A normal component without onigiri compilation
    // This renders actual VNodes that get serialized at runtime
    const NormalComponent = defineComponent({
      props: {
        msg: String,
      },
      setup(props) {
        // No onigiri check - just a normal component
        return () => h("div", { class: "normal" }, props.msg);
      },
    });

    const result = await renderToSerializedVNode(NormalComponent, {
      msg: "test",
    });

    // Should serialize the rendered output via runtime fallback
    expect(result).toBeDefined();
    expect(result![0]).toBe(VServerComponentType.Element);
    expect(result![1]).toBe("div");
  });

  it("should handle async setup with onigiri mode", async () => {
    // For async setup, the inject must happen synchronously at the start
    const AsyncComponent = defineComponent({
      setup() {
        // Check for onigiri mode FIRST (synchronously)
        const onigiriMode = inject(ONIGIRI_RENDER_SYMBOL, null);
        
        // Then do async work
        const data = ref("initial");
        
        if (onigiriMode) {
          // Return async function that will be awaited
          return async () => {
            await Promise.resolve();
            data.value = "async data";
            return [VServerComponentType.Text, data.value] as const;
          };
        }

        return { data };
      },
    });

    const result = await renderToSerializedVNode(AsyncComponent);

    expect(result).toEqual([VServerComponentType.Text, "async data"]);
  });
});

describe("ONIGIRI_RENDER_SYMBOL", () => {
  it("should be a symbol", () => {
    expect(typeof ONIGIRI_RENDER_SYMBOL).toBe("symbol");
  });

  it("should be injectable", () => {
    // The symbol should work with Vue's inject/provide
    expect(ONIGIRI_RENDER_SYMBOL.toString()).toContain("onigiri");
  });
});
