import { renderSlot as _renderSlot, Slots, VNodeArrayChildren, } from "vue"

export function renderSlot(
    ctx,
    slots: Slots,
    name: string,
    props = {},
    // this is not a user-facing function, so the fallback is always generated by
    // the compiler and guaranteed to be a function returning an array
    fallback?: () => VNodeArrayChildren,
    noSlotted?: boolean,
) {
    const result = _renderSlot(
        slots,
        name,
        props,
        fallback,
        noSlotted,
    )

    ctx.$.__slotsResult = ctx.__slotsResult || {}
    ctx.$.__slotsResult[name] = result
    return result
}