import { renderSlot as _renderSlot } from "vue";
import type { Slots, VNodeArrayChildren } from "vue";

export function renderSlot(
  ctx: any,
  slots: Slots,
  name: string,
  props = {},
  // this is not a user-facing function, so the fallback is always generated by
  // the compiler and guaranteed to be a function returning an array
  fallback?: () => VNodeArrayChildren,
  noSlotted?: boolean,
) {
  const result = _renderSlot(slots, name, props, fallback, noSlotted);

  ctx._.__slotsResult = ctx._.__slotsResult || {};
  ctx._.__slotsResult[name] = result;
  return result;
}
